config/routes.rb
Rails.application.routes.draw do
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  root "movies#index"
  resources :movies
  resources :questions do
    resource :answers, only: [:create, :edit, :update, :destroy]
  end
  resources :aws_texts, only: [:index, :show]
  resources :aws_texts do
    resource :read_texts, only: [:create, :destroy]
  end
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/answer.rb
class Answer < ApplicationRecord
  belongs_to :user
  belongs_to :question  
  validates :content, presence: true, length: { maximum: 5000 }
  validates :user_id, uniqueness: {
    scope: :question_id,
    message: "は同じ質問に２以上の回答はできません"
  }
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/aws_text.rb
class AwsText < ApplicationRecord
  has_many :read_texts, dependent: :destroy
  has_many :read_texted_users, through: :likes, source: :user
  validates :title, :content, presence: true

  def read_text_by?(user)
    read_texts.find_by(user_id: user.id).present?
  end
end

app/models/movie.rb
class Movie < ApplicationRecord
  validates :title, :url, presence: true
end

app/models/question.rb
class Question < ApplicationRecord
    validates :title, presence: true, length: { maximum: 100}
    validates :detail, presence: true, length: { maximum: 5000 }
    belongs_to :user
    has_many :answers, dependent: :destroy

    # 質問にuserが回答している時は[true]、回答していない時は[false]
    def answerd_by?(user)
        answers.find_by(user_id: user.id).present?
    end
end

app/models/read_text.rb
class ReadText < ApplicationRecord
  belongs_to :user
  belongs_to :aws_text
  validates :user_id, uniqueness: {
                        scope: :aws_text_id,
                      }
end

app/models/ruby.rb
class Ruby < ApplicationRecord
  validates :title, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  has_many :questions, dependent: :destroy
  has_many :answers,   dependent: :destroy
  has_many :read_texts, dependent: :destroy
  has_many :read_texted_movies, through: :read_texts, source: :movie
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController

  before_action :set_answer, only: %i[edit update destroy]

  def create
    @answer = current_user.answers.new(answer_params)
    if @answer.save
      flash[:notice] = "回答を投稿しました"
      @question = Question.find(params[:question_id])
      redirect_to @question
    else
      @question = Question.find(params[:question_id])
      @answers = @question.answers
      flash.now[:alert] = "回答の投稿に失敗しました"
      render "questions/show"
    end
  end

  def edit

  end

  def update
    @answer.update!(answer_params)
    redirect_to @answer, notice: "回答を更新しました"
  end

  def destroy
    current_user.answers.find_by(question_id: params[:question_id]).destroy!
    redirect_to @answer
  end

  private

  def answer_params
    params.require(:answer).permit(:content).merge params.permit(:question_id)
  end

  def set_answer
    @answer = current_user.answer.find(params[:id])  
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :authenticate_user!
end

app/controllers/aws_texts_controller.rb
class AwsTextsController < ApplicationController
  def index
    @aws_texts=AwsText.all
  end

  def show
    @aws_text = AwsText.find(params[:id])
  end

end

app/controllers/movies_controller.rb
class MoviesController < ApplicationController
  # 1ページの表示数
  PER_PAGE = 20
  def index
    if params[:genre].present?
      @q = Movie.where(genre: params[:genre]).ransack(params[:q])
      @movies = @q.result.page(params[:page]).per(PER_PAGE)
    else
      @q = Movie.where(genre: ["Basic", "Git", "Ruby", "Ruby on Rails"]).ransack(params[:q])
      @movies = @q.result.page(params[:page]).per(PER_PAGE)
    end
  end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController

  before_action :set_question, only: %i[edit update destroy]

  def index
    @question = Question.new
    @questions = Question.order(id: :desc).includes(:user)
  end

  def show
    @question = Question.all
    @question = Question.find(params[:id])
    @answers = @question.answers
    @answer = Answer.new
  end

  def new

  end

  def create
    @question = current_user.questions.new(question_params)
    if @question.save
      redirect_to @question, notice: "質問を投稿しました"
    else
      @questions = Question.order(id: :desc).includes(:user)
      flash.now[:alert] = "投稿に失敗しました" 
      render :index
    end
  end

  def edit
  end

  def update
    if @question.update(question_params)
      redirect_to @question, notice: "質問を更新しました"      
    else
      flash.now[:alert] = "質問の更新に失敗しました"
      render :edit
    end
  end

  def destroy
    @question.destroy!
    redirect_to @question, notice: "質問を削除しました"
  end

  private
  
  def question_params
    params.require(:question).permit(:title, :detail)
  end

  def set_question
    @question = current_user.questions.find(params[:id]) 
  end

end

app/controllers/read_texts_controller.rb
class ReadTextsController < ApplicationController
  def create
    @aws_text = AwsText.find(params[:aws_text_id])
    current_user.read_texts.create!(aws_text_id: @aws_text.id)
  end

  def destroy
    @aws_text = AwsText.find(params[:aws_text_id])
    current_user.read_texts.find_by(aws_text_id: @aws_text.id).destroy!
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  require "redcarpet"
  require "coderay"

  class HTMLwithCoderay < Redcarpet::Render::HTML
    def block_code(code, language)
            language = language.split(':')[0] if language.present?

            case language.to_s
            when 'rb'
                lang = :ruby
            when 'yml'
                lang = :yaml
            when 'css'
                lang = :css
            when 'html'
                lang = :html
            when ''
                lang = :md
            else
                lang = language
            end

            CodeRay.scan(code, lang).div
        end
    end

    def markdown(text)
        html_render = HTMLwithCoderay.new(
          filter_html: true,
          hard_wrap: true,
          link_attributes: { rel: 'nofollow', target: "_blank" }
        )
        options = {
            autolink: true,
            space_after_headers: true,
            no_intra_emphasis: true,
            fenced_code_blocks: true,
            tables: true,
            hard_wrap: true,
            xhtml: true,
            lax_html_blocks: true,
            strikethrough: true
        }
        markdown = Redcarpet::Markdown.new(html_render, options)
        markdown.render(text).html_safe
    end
  end

app/views/aws_texts/_disread_text.html.erb
<%= link_to "読破済みにする", aws_text_read_texts_path(aws_text), class: "btn btn-secondary btn-block", method: :post, remote: true %>

app/views/aws_texts/_read_text.html.erb
<%= link_to "読破ずみを解除する", aws_text_read_texts_path(aws_text), class: "btn btn-primary btn-block", method: :delete, remote: true %>

app/views/aws_texts/index.html.erb
<h1 class="text-center">AWS講座</h1>
<p>注意！！！：AWSのEC2やRDSは有料サービスとなります。無駄な料金を請求されないためにも、不要なインスタンスは停止・削除をしてください。</p>
<table class="table table-striped">
  <thead class="bg-primary text-white">
    <tr>
      <th scope="col">NO.</th>
      <th scope="col">内容</th>
    </tr>
  </thead>
  <tbody>
    <% @aws_texts.each_with_index do |aws_text,i|%>
      <tr>
        <th scope="row"><%= i+1 %></th>
        <td><%= link_to aws_text.title, aws_text %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/aws_texts/show.html.erb
<h2><%= markdown(@aws_text.title) %></h2>
<p>
  <%= markdown(@aws_text.content) %>
  <p id="aws_text-<%= @aws_text.id %>">
    <% if @aws_text.read_text_by?(current_user) %>
      <%# 「いいね！」済み %>
      <%= render "read_text", aws_text: @aws_text %>
    <% else %>
      <%# 「いいね」していない %>
      <%= render "disread_text", aws_text: @aws_text %>
    <% end %>
  </p>
</p>

app/views/layouts/_flash.html.erb
<% flash.each do |flash_type, msg| %>
  <div class="alert alert-<%= flash_type %>" role="alert">
    <a href="#" class="close" data-dismiss="alert">×</a>
    <%= msg %>
  </div>
<% end %>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary fixed-top">
  <a class="navbar-brand" href="#">やんばるCODE</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTogglerDemo02" aria-controls="navbarTogglerDemo02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarTogglerDemo02">
    <ul class="navbar-nav mr-auto mt-2 mt-lg-0">
      <% if user_signed_in? %>
        <li class="nav-item active dropdown">
            <button class="btn dropdown-toggle " type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              Rails
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to "Ruby/Rails教材", "#",class: "dropdown-item" %>
              <%= link_to "動画教材", movies_path,class: "dropdown-item" %>
              <%= link_to "AWS講座", aws_texts_path,class: "dropdown-item" %>
              <%= link_to "プログラミング勉強会", movies_path(genre: "Live"),class: "dropdown-item" %>
              <%= link_to "質問集", questions_path,class: "dropdown-item" %>
            </div>
        </li>
        <li class="nav-item">
          <%= link_to "対談", movies_path(genre: "Talk"),class: "nav-item nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "情報発信", movies_path(genre: "Marketing"),class: "nav-item nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "動画編集講座", movies_path(genre: "Movie"),class: "nav-item nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "ライティング講座", movies_path(genre: "Writing"),class: "nav-item nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "マネタイズ講座", movies_path(genre: "Money"),class: "nav-item nav-link active" %>
        </li>
        <li class="nav-item active dropdown">
            <button class="btn  dropdown-toggle" type="button" id="dropdownMenuButton" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false">
              PHP
            </button>
            <div class="dropdown-menu" aria-labelledby="dropdownMenuButton">
              <%= link_to "PHPテキスト教材", "#",class: "dropdown-item" %>
              <%= link_to "PHP動画教材", movies_path(genre: "Php"),class: "dropdown-item" %>
            </div>
        </li>
        <li class="nav-item">
          <%= link_to "LINE@", "#",class: "nav-item nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "マイページ", "#",class: "nav-item nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "ログアウト", destroy_user_session_path, method: :delete, data: { confirm: "ログアウトしますか？" },class: "nav-item nav-link active" %>
        </li>
      <% else %>
        <li class="nav-item">
          <%= link_to "ログイン", new_user_session_path,class: "nav-item nav-link active" %>
        </li>
        <li class="nav-item">
          <%= link_to "新規登録", new_user_registration_path,class: "nav-item nav-link active" %>
        </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>GyakutenCloneGroup</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= stylesheet_pack_tag "application", media: "all", "data-turbolinks-track": "reload" %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <header>
      <%= render "layouts/header" %>
    </header>
    <main>
      <%= render "layouts/flash" %>
      <div class="base-container">
        <%= yield %>
      </div>
    </main>
    <footer>

    </footer>
  </body>
</html>

app/views/movies/index.html.erb
<div class="container">
  <%= search_form_for @q do |f|%>
    <div class="input-group  my-4" >
      <%= f.search_field :title_cont,class:"form-control col-sm-4 col-lg-3",placeholder:"キーワード検索"%>
      <%= f.submit "検索",class:"btn btn-primary"%>
    </div>
  <% end %>
  <div class="row">
    <%@movies.each.with_index(@movies.offset_value + 1) do |movie,i|%>
      <div class="col-sm-6 col-lg-4 card-columns card-deck" >
        <div class="card " style="width: 25rem;">
          <div class="embed-responsive embed-responsive-16by9">
            <iframe class="embed-responsive-item" src="<%=movie.url%>" allowfullscreen></iframe>
          </div>
          <div class="card-body" style="height: 15rem;">
            <h4 class="card-text">Lv.<%= i %>：<span class="movie_title"><%= movie.title %></span></h4>
          </div>
        </div>
      </div>
    <% end %>
    <%= paginate @movies %>
  </div>
</div>

app/views/questions/_form.html.erb
<%= form_with model: @question, local: true do |form| %>
<%# 質問フォーム %>
  <div class="form-group">
    <%= form.label :title, "【質問】" %>
    <%= form.text_area :title, class: "form-control" %>
  </div>
<%# 詳細フォーム %>
  <div class="form-group">
    <%= form.label :detail, "【詳細】" %>
    <%= form.text_area :detail, class: "form-control" %>
  </div>
<%# 送信ボタン %>
  <div>
    <%= form.submit "送信", class: "btn btn-primary btn-block" %>
  </div>
<% end %>

app/views/questions/edit.html.erb
<h2>編集</h2>
<%= render "form" %>

app/views/questions/index.html.erb
<h2>新規投稿</h2>

 <%= render "form" %>

<%# 質問一覧を降順表示 %>
<table>
  <tbody>
    <% @questions.each.with_index(1) do |question, i| %>
      <tr>
        <td>
        <button type="button" class="btn btn-outline-light btn-lg btn-block"><%= link_to question.title, question %></button>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/questions/new.html.erb
<h2>新規投稿</h2>
<%= render "form" %>

app/views/questions/show.html.erb
<p>【質問】<br> <%= markdown(@question.title) %></p>
<p>【詳細】<br> <%= markdown(@question.detail) %></p>

<h3>回答</h3>
<% @answers.each do |a| %>
  <div>
    <%= markdown(a.content) %>
  </div>
  <hr>
<% end %>

<%# 質問に対してuserが回答しているか否かで回答フォームの表示・非表示を切り替え %>
<% if @question.answerd_by?(current_user) %>
  <%# <p>
    <%= link_to "回答編集", edit_answer_path(@answer) %>
    <%# <%= link_to "回答削除", answer_path(@answer), method: :delete, data: { confirm: "削除しますか？" } %>
  <%# </p> %>
<% else %>
  <h2>回答投稿</h2>
    <%= form_with model: [@question, @answer], local: true do |form| %>
      <div class="form-group">
        <%= form.label :title, "【回答】" %>
        <%= form.text_area :content, class: "form-control" %>
      </div>

      <div>
        <%= form.submit "送信", class: "btn btn-primary btn-block" %>
      </div>
    <% end %>
<% end %>

<%# 質問が自分の投稿であれば編集、削除ボタンを表示 %>
<% if current_user.id == @question.user.id  %>
  <p>
    <%= link_to "編集", edit_question_path(@question) %>
    <%= link_to "削除", question_path(@question), method: :delete, data: { confirm: "削除しますか？" } %>
  </p>
<% end %>
<p><%= link_to "質問一覧へ", questions_path %></p>

app/views/read_texts/create.js.erb
document.getElementById('aws_text-<%= @aws_text.id %>').innerHTML = '<%= j render("aws_texts/read_text", aws_text: @aws_text) %>'

app/views/read_texts/destroy.js.erb
document.getElementById('aws_text-<%= @aws_text.id %>').innerHTML = '<%= j render("aws_texts/disread_text", aws_text: @aws_text) %>'